"""add direct account permissions

Revision ID: 070c6af80222
Revises: 945f674768b4
Create Date: 2026-08-26 21:03:37.038915

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "070c6af80222"
down_revision: str | Sequence[str] | None = "945f674768b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_permissions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "permission_id", name="uq_account_permissions"
        ),
    )
    op.create_index(
        op.f("ix_account_permissions_account_id"),
        "account_permissions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_permissions_permission_id"),
        "account_permissions",
        ["permission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_permissions_permission_id"), table_name="account_permissions"
    )
    op.drop_index(
        op.f("ix_account_permissions_account_id"), table_name="account_permissions"
    )
    op.drop_table("account_permissions")
    # ### end Alembic commands ###
