"""Add rejection_reason to seller_listings

Revision ID: 634badbf38ec
Revises: eae5263f1fbc
Create Date: 2026-08-27 08:47:20.050153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634badbf38ec'
down_revision: Union[str, Sequence[str], None] = 'eae5263f1fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_listings', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_listings', 'rejection_reason')
    # ### end Alembic commands ###
