"""add sellers and seller documents

Revision ID: 90d3c374c24e
Revises: 070c6af80222
Create Date: 2026-08-26 23:00:27.350479

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90d3c374c24e"
down_revision: str | Sequence[str] | None = "070c6af80222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.String(length=150), nullable=False),
        sa.Column("business_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sellers_account_id"), "sellers", ["account_id"], unique=True
    )
    op.create_index(
        op.f("ix_sellers_business_name"), "sellers", ["business_name"], unique=True
    )
    op.create_index(op.f("ix_sellers_status"), "sellers", ["status"], unique=False)
    op.create_table(
        "seller_documents",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=False),
        sa.Column("cloudinary_resource_type", sa.String(length=20), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seller_id", "document_type", name="uq_seller_documents_type"
        ),
    )
    op.create_index(
        op.f("ix_seller_documents_document_type"),
        "seller_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seller_documents_seller_id"),
        "seller_documents",
        ["seller_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seller_documents_seller_id"), table_name="seller_documents")
    op.drop_index(
        op.f("ix_seller_documents_document_type"), table_name="seller_documents"
    )
    op.drop_table("seller_documents")
    op.drop_index(op.f("ix_sellers_status"), table_name="sellers")
    op.drop_index(op.f("ix_sellers_business_name"), table_name="sellers")
    op.drop_index(op.f("ix_sellers_account_id"), table_name="sellers")
    op.drop_table("sellers")
    # ### end Alembic commands ###
