"""add permission metadata columns and cascade role_permissions delete

Revision ID: 945f674768b4
Revises: 8f020f9eafd8
Create Date: 2026-08-26 20:30:42.226534

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "945f674768b4"
down_revision: str | Sequence[str] | None = "8f020f9eafd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions", sa.Column("name", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "permissions", sa.Column("resource", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "permissions", sa.Column("action", sa.String(length=50), nullable=False)
    )
    op.create_index(
        op.f("ix_permissions_resource"), "permissions", ["resource"], unique=False
    )
    op.drop_constraint(
        op.f("role_permissions_permission_id_fkey"),
        "role_permissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.create_foreign_key(
        op.f("role_permissions_permission_id_fkey"),
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_permissions_resource"), table_name="permissions")
    op.drop_column("permissions", "action")
    op.drop_column("permissions", "resource")
    op.drop_column("permissions", "name")
    # ### end Alembic commands ###
