"""Add created_by_seller_id to products

Revision ID: 9d7a3e9ff124
Revises: ac0cb888362c
Create Date: 2026-08-27 10:09:40.004252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7a3e9ff124'
down_revision: Union[str, Sequence[str], None] = 'ac0cb888362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by_seller_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_created_by_seller_id'), 'products', ['created_by_seller_id'], unique=False)
    op.create_foreign_key(None, 'products', 'sellers', ['created_by_seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_created_by_seller_id'), table_name='products')
    op.drop_column('products', 'created_by_seller_id')
    # ### end Alembic commands ###
