"""add premium plans and seller subscriptions

Revision ID: a7f62ec3797d
Revises: 9d7a3e9ff124
Create Date: 2026-08-27 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7f62ec3797d"
down_revision: str | Sequence[str] | None = "9d7a3e9ff124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "premium_plans",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("listing_limit", sa.Integer(), nullable=False),
        sa.Column("premium_badge", sa.Boolean(), nullable=False),
        sa.Column("unlimited_listings", sa.Boolean(), nullable=False),
        sa.Column("priority_notifications", sa.Boolean(), nullable=False),
        sa.Column("early_promotion_access", sa.Boolean(), nullable=False),
        sa.Column("premium_only_promotions", sa.Boolean(), nullable=False),
        sa.Column("premium_discounts", sa.Boolean(), nullable=False),
        sa.Column("enhanced_favorites", sa.Boolean(), nullable=False),
        sa.Column("priority_support", sa.Boolean(), nullable=False),
        sa.Column("priority_service_handling", sa.Boolean(), nullable=False),
        sa.Column("referral_commission_eligible", sa.Boolean(), nullable=False),
        sa.Column("enhanced_visibility", sa.Boolean(), nullable=False),
        sa.Column("promotional_advantages", sa.Boolean(), nullable=False),
        sa.Column("advanced_analytics", sa.Boolean(), nullable=False),
        sa.Column("seller_verification_eligible", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_premium_plans_code"), "premium_plans", ["code"], unique=True)
    op.create_table(
        "seller_subscriptions",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"]),
        sa.ForeignKeyConstraint(["plan_id"], ["premium_plans.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seller_subscriptions_seller_id"),
        "seller_subscriptions",
        ["seller_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seller_subscriptions_status"),
        "seller_subscriptions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seller_subscriptions_plan_id"),
        "seller_subscriptions",
        ["plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_seller_subscriptions_plan_id"), table_name="seller_subscriptions"
    )
    op.drop_index(
        op.f("ix_seller_subscriptions_status"), table_name="seller_subscriptions"
    )
    op.drop_index(
        op.f("ix_seller_subscriptions_seller_id"), table_name="seller_subscriptions"
    )
    op.drop_table("seller_subscriptions")
    op.drop_index(op.f("ix_premium_plans_code"), table_name="premium_plans")
    op.drop_table("premium_plans")
    # ### end Alembic commands ###
