"""Cascade role_id deletes on account_roles and role_permissions

Revision ID: ac0cb888362c
Revises: 634badbf38ec
Create Date: 2026-08-27 08:51:48.152137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0cb888362c'
down_revision: Union[str, Sequence[str], None] = '634badbf38ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_roles_role_id_fkey'), 'account_roles', type_='foreignkey')
    op.create_foreign_key(None, 'account_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'account_roles', type_='foreignkey')
    op.create_foreign_key(op.f('account_roles_role_id_fkey'), 'account_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
