"""add_unique_constraint_category_parent_name

Revision ID: eae5263f1fbc
Revises: af3d6a201715
Create Date: 2026-08-27 01:22:32.846453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae5263f1fbc'
down_revision: Union[str, Sequence[str], None] = 'af3d6a201715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_categories_parent_name', 'categories', ['parent_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_parent_name', 'categories', type_='unique')
    # ### end Alembic commands ###
