import type {
  Product,
  Order,
  Payment,
  Earning,
  NavItem,
} from "./types";

export const COMMISSION_RATE = 0.1; // 10%

// NOTE: users array removed — users page now uses real API (GET /sellers + /auth/accounts)

export const products: Product[] = [
  {
    id: "p1",
    name: "Organic Arabica Coffee",
    price: 12.5,
    category: "Food & Beverage",
    unit: "kg",
    sellerId: "u2",
    sellerName: "James Ochieng",
    stock: 50,
    description: "Premium single-origin Arabica coffee beans from the highlands of Ethiopia.",
    createdAt: "2024-06-01",
  },
  {
    id: "p2",
    name: "Handwoven Kikoy Fabric",
    price: 28.0,
    category: "Clothing",
    unit: "piece",
    sellerId: "u2",
    sellerName: "James Ochieng",
    stock: 30,
    description: "Traditional East African kikoy fabric, hand-woven with vibrant patterns.",
    createdAt: "2024-06-03",
  },
  {
    id: "p3",
    name: "Shea Butter Moisturizer",
    price: 9.99,
    category: "Health & Beauty",
    unit: "100ml",
    sellerId: "u3",
    sellerName: "Sarah Nkosi",
    stock: 80,
    description: "Pure unrefined shea butter sourced from West Africa. Great for skin and hair.",
    createdAt: "2024-06-05",
  },
  {
    id: "p4",
    name: "Moringa Powder",
    price: 7.5,
    category: "Health & Beauty",
    unit: "250g",
    sellerId: "u3",
    sellerName: "Sarah Nkosi",
    stock: 120,
    description: "100% organic moringa leaf powder, rich in vitamins and minerals.",
    createdAt: "2024-06-07",
  },
  {
    id: "p5",
    name: "Wooden Salad Bowl Set",
    price: 35.0,
    category: "Home & Garden",
    unit: "set",
    sellerId: "u6",
    sellerName: "David Mugisha",
    stock: 15,
    description: "Hand-carved acacia wood salad bowl set. Includes 1 large and 4 small bowls.",
    createdAt: "2024-06-10",
  },
  {
    id: "p6",
    name: "Beaded Maasai Bracelet",
    price: 14.0,
    category: "Clothing",
    unit: "piece",
    sellerId: "u6",
    sellerName: "David Mugisha",
    stock: 60,
    description: "Authentic hand-beaded Maasai bracelet. Each piece is unique.",
    createdAt: "2024-06-12",
  },
  {
    id: "p7",
    name: "Solar Lantern",
    price: 22.0,
    category: "Electronics",
    unit: "piece",
    sellerId: "u2",
    sellerName: "James Ochieng",
    stock: 25,
    description: "Portable solar-powered LED lantern. Charges in 6 hours, lasts 12 hours.",
    createdAt: "2024-06-15",
  },
  {
    id: "p8",
    name: "Baobab Fruit Powder",
    price: 11.0,
    category: "Food & Beverage",
    unit: "200g",
    sellerId: "u3",
    sellerName: "Sarah Nkosi",
    stock: 90,
    description: "Dried baobab fruit powder, high in vitamin C and antioxidants.",
    createdAt: "2024-06-18",
  },
];

export const orders: Order[] = [
  {
    id: "ord1",
    clientId: "u1",
    clientName: "Amina M.",
    sellerId: "u2",
    sellerName: "James Ochieng",
    items: [
      { productId: "p1", productName: "Organic Arabica Coffee", price: 12.5, quantity: 2, unit: "kg", sellerName: "James Ochieng" },
    ],
    total: 25.0,
    status: "delivered",
    paymentStatus: "completed",
    createdAt: "2024-07-01",
  },
  {
    id: "ord2",
    clientId: "u1",
    clientName: "Amina M.",
    sellerId: "u3",
    sellerName: "Sarah Nkosi",
    items: [
      { productId: "p3", productName: "Shea Butter Moisturizer", price: 9.99, quantity: 1, unit: "100ml", sellerName: "Sarah Nkosi" },
      { productId: "p4", productName: "Moringa Powder", price: 7.5, quantity: 2, unit: "250g", sellerName: "Sarah Nkosi" },
    ],
    total: 24.99,
    status: "processing",
    paymentStatus: "completed",
    createdAt: "2024-07-10",
  },
  {
    id: "ord3",
    clientId: "u5",
    clientName: "Fatima Hassan",
    sellerId: "u6",
    sellerName: "David Mugisha",
    items: [
      { productId: "p5", productName: "Wooden Salad Bowl Set", price: 35.0, quantity: 1, unit: "set", sellerName: "David Mugisha" },
    ],
    total: 35.0,
    status: "shipped",
    paymentStatus: "completed",
    createdAt: "2024-07-12",
  },
  {
    id: "ord4",
    clientId: "u1",
    clientName: "Amina M.",
    sellerId: "u6",
    sellerName: "David Mugisha",
    items: [
      { productId: "p6", productName: "Beaded Maasai Bracelet", price: 14.0, quantity: 3, unit: "piece", sellerName: "David Mugisha" },
    ],
    total: 42.0,
    status: "pending",
    paymentStatus: "pending",
    createdAt: "2024-07-15",
  },
  {
    id: "ord5",
    clientId: "u5",
    clientName: "Fatima Hassan",
    sellerId: "u2",
    sellerName: "James Ochieng",
    items: [
      { productId: "p7", productName: "Solar Lantern", price: 22.0, quantity: 2, unit: "piece", sellerName: "James Ochieng" },
    ],
    total: 44.0,
    status: "delivered",
    paymentStatus: "completed",
    createdAt: "2024-07-18",
  },
];

export const payments: Payment[] = [
  {
    id: "pay1",
    orderId: "ord1",
    clientName: "Amina M.",
    sellerName: "James Ochieng",
    amount: 25.0,
    commission: 2.5,
    sellerPayout: 22.5,
    status: "completed",
    payoutStatus: "sent",
    createdAt: "2024-07-01",
  },
  {
    id: "pay2",
    orderId: "ord2",
    clientName: "Amina M.",
    sellerName: "Sarah Nkosi",
    amount: 24.99,
    commission: 2.5,
    sellerPayout: 22.49,
    status: "completed",
    payoutStatus: "sent",
    createdAt: "2024-07-10",
  },
  {
    id: "pay3",
    orderId: "ord3",
    clientName: "Fatima Hassan",
    sellerName: "David Mugisha",
    amount: 35.0,
    commission: 3.5,
    sellerPayout: 31.5,
    status: "completed",
    payoutStatus: "pending",
    createdAt: "2024-07-12",
  },
  {
    id: "pay4",
    orderId: "ord4",
    clientName: "Amina M.",
    sellerName: "David Mugisha",
    amount: 42.0,
    commission: 4.2,
    sellerPayout: 37.8,
    status: "pending",
    payoutStatus: "pending",
    createdAt: "2024-07-15",
  },
  {
    id: "pay5",
    orderId: "ord5",
    clientName: "Fatima Hassan",
    sellerName: "James Ochieng",
    amount: 44.0,
    commission: 4.4,
    sellerPayout: 39.6,
    status: "completed",
    payoutStatus: "pending",
    createdAt: "2024-07-18",
  },
];

export const earnings: Earning[] = [
  {
    id: "e1",
    orderId: "ord1",
    productName: "Organic Arabica Coffee",
    clientName: "Amina M.",
    grossAmount: 25.0,
    commission: 2.5,
    netAmount: 22.5,
    payoutStatus: "sent",
    createdAt: "2024-07-01",
  },
  {
    id: "e2",
    orderId: "ord5",
    productName: "Solar Lantern",
    clientName: "Fatima Hassan",
    grossAmount: 44.0,
    commission: 4.4,
    netAmount: 39.6,
    payoutStatus: "pending",
    createdAt: "2024-07-18",
  },
];

export const navItems: NavItem[] = [
  { label: "Overview", icon: "LayoutDashboard", href: "/dashboard", roles: ["client", "seller", "admin"] },
  { label: "Browse Products", icon: "ShoppingBag", href: "/dashboard/products", roles: ["client"] },
  { label: "My Cart", icon: "ShoppingCart", href: "/dashboard/cart", count: 2, roles: ["client"] },
  { label: "My Orders", icon: "Package", href: "/dashboard/orders", roles: ["client"] },
  { label: "My Products", icon: "Store", href: "/dashboard/products", roles: ["seller"] },
  { label: "My Listings", icon: "Tag", href: "/dashboard/listings", roles: ["seller"] },
  { label: "Create Listing", icon: "Plus", href: "/dashboard/listings/new", roles: ["seller"] },
  { label: "Orders Received", icon: "ClipboardList", href: "/dashboard/orders", roles: ["seller"] },
  { label: "My Earnings", icon: "Wallet", href: "/dashboard/earnings", roles: ["seller"] },
  { label: "Seller Profile", icon: "Store", href: "/dashboard/seller", roles: ["seller"] },
  { label: "All Orders", icon: "ClipboardList", href: "/dashboard/orders", roles: ["admin"] },
  { label: "Payments", icon: "CreditCard", href: "/dashboard/payments", count: 3, roles: ["admin"] },
  { label: "Seller Review", icon: "UserCheck", href: "/dashboard/sellers", roles: ["admin"] },
  { label: "Product Review", icon: "Package", href: "/dashboard/products", roles: ["admin"] },
  { label: "Listing Review", icon: "Tag", href: "/dashboard/listings", roles: ["admin"] },
  { label: "Catalog Setup", icon: "Layers", href: "/dashboard/catalog", roles: ["admin"] },
  { label: "Users", icon: "Users", href: "/dashboard/users", roles: ["admin"] },
];

export const bottomNavItems: NavItem[] = [
  { label: "Profile", icon: "User", href: "/dashboard/profile", roles: ["client", "seller", "admin"] },
  { label: "Settings", icon: "Settings", href: "/dashboard/settings", roles: ["client", "seller", "admin"] },
];
